### ISSUE TITLE
Version 1.0 release?  Drop PHP < 7.4? <8.0?

### ISSUE THREAD

**Issue by tacman** [opsway/doctrine-dbal-postgresql#37]
Thoughts on a 1.0 release?

PHP 5.6 has been dead since 2018, what do you think about dropping support for anything less than php 7.4?  Actually, 7.4 will be at EOL in 4 months, since this would be a new release, perhaps you could simply require PHP8, and take advantage of all the goodies it provides.

**Comment by damienfa** [comment]
As a matter of priority, we would need a new tag "1.0" with the `master` version.
For 2 years now, I'm using `composer require  opsway/doctrine-dbal-postgresql:dev-master` … 

Totally agree with the drop of PHP < 7.4… or even < 8.0.

**Comment by shandyDev** [comment]
DBAL >3.2 still support PHP 7.4, so no sense drop it now.
Major version v1.0 was released. Support for PHP <=7.3 was dropped.
