### ISSUE TITLE
How to use TS_MATCH_OP

### ISSUE THREAD

**Issue by dungdc40** [opsway/doctrine-dbal-postgresql#9]
Hi,

I registered TS_MTACH_OP to doctrine:
$config
->addCustomStringFunction('TS_MATCH_OP','Opsway\Doctrine\ORM\Query\AST\Functions\TsMatch');

In my resource file, I have this query:
$query = $this->em->createQuery('SELECT u FROM App\Entity\Users u WHERE TS_MATCH_OP( u.nameFTS, :name)');
$query->setParameter('name', 'Bob');
$users = $query->getResult();

but I have errors:
1. Doctrine\ORM\Query\QueryException
   Message: SELECT u FROM App\Entity\Users u WHERE TS_MATCH_OP( u.nameFTS, :name)
2. Doctrine\ORM\Query\QueryException
   [Syntax Error] line 0, col -1: Error: Expected =, <, <=, <>, >, >=, !=, got end of string

Can you help me with this error?

**Comment by shandyDev** [comment]
This is doctrine feature, DQL function should have result.
So in your DQL you should use math operator for comparsion results:
SELECT u FROM App\Entity\Users u WHERE TS_MATCH_OP( u.nameFTS, :name) == true
